import React from 'react';
import { Chip, Tooltip } from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import StorageIcon from '@mui/icons-material/Storage';
import CachedIcon from '@mui/icons-material/Cached';
import HelpOutlineIcon from '@mui/icons-material/HelpOutline';

interface ProvenanceBadgeProps {
  dataSource?: 'ai_analysis' | 'ai_assisted' | 'db' | 'fallback' | string;
  generatedAt?: string; // ISO timestamp
  cacheAgeHours?: number;
}

const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({ 
  dataSource, 
  generatedAt,
  cacheAgeHours 
}) => {
  // Calculate age from generatedAt if not provided directly
  const getAge = (): { text: string; hours: number } | null => {
    if (cacheAgeHours !== undefined) {
      return { text: formatAge(cacheAgeHours), hours: cacheAgeHours };
    }
    if (!generatedAt) return null;
    
    const generatedDate = new Date(generatedAt);
    const now = new Date();
    const hoursOld = (now.getTime() - generatedDate.getTime()) / (1000 * 60 * 60);
    
    return { text: formatAge(hoursOld), hours: hoursOld };
  };

  const formatAge = (hours: number): string => {
    if (hours < 1) {
      const minutes = Math.round(hours * 60);
      return `${minutes} minute${minutes !== 1 ? 's' : ''}`;
    }
    if (hours < 24) {
      const h = Math.round(hours);
      return `${h} hour${h !== 1 ? 's' : ''}`;
    }
    const days = Math.round(hours / 24);
    return `${days} day${days !== 1 ? 's' : ''}`;
  };

  const age = getAge();

  // Determine label, icon, and color based on data source and age
  const getBadgeConfig = () => {
    switch (dataSource) {
      case 'ai_analysis':
        if (age && age.hours < 1) {
          return {
            label: `Fresh AI Analysis (${age.text} old)`,
            icon: <AutoAwesomeIcon />,
            color: 'success' as const,
            tooltip: 'Data was generated by AI analysis less than 1 hour ago'
          };
        }
        if (age) {
          return {
            label: `Cached AI Analysis (${age.text} old)`,
            icon: <CachedIcon />,
            color: 'warning' as const,
            tooltip: `Data was generated ${age.text} ago and may be stale`
          };
        }
        return {
          label: 'AI Analysis',
          icon: <AutoAwesomeIcon />,
          color: 'info' as const,
          tooltip: 'Data was generated by AI analysis'
        };

      case 'ai_assisted':
        return {
          label: 'AI-Assisted',
          icon: <AutoAwesomeIcon />,
          color: 'info' as const,
          tooltip: 'Data was generated with AI assistance'
        };

      case 'db':
      case 'database':
        return {
          label: 'DB-Grounded',
          icon: <StorageIcon />,
          color: 'primary' as const,
          tooltip: 'Data is grounded in your database records'
        };

      case 'fallback':
        return {
          label: 'Fallback Data',
          icon: <HelpOutlineIcon />,
          color: 'default' as const,
          tooltip: 'Data is from a fallback source due to missing primary data'
        };

      default:
        return {
          label: 'Unknown Source',
          icon: <HelpOutlineIcon />,
          color: 'default' as const,
          tooltip: 'Data source is not specified'
        };
    }
  };

  const config = getBadgeConfig();

  return (
    <Tooltip title={config.tooltip} arrow>
      <Chip
        icon={config.icon}
        label={config.label}
        color={config.color}
        size="small"
        variant="outlined"
      />
    </Tooltip>
  );
};

export default ProvenanceBadge;