DEFAULT_SUBSCRIPTION_PLANS = [
    {
        "name": "Free",
        "tier": "free",
        "price_monthly": 0.0,
        "price_yearly": 0.0,
        "ai_text_generation_calls_limit": 50,
        "gemini_calls_limit": 50,
        "openai_calls_limit": 0,
        "anthropic_calls_limit": 0,
        "mistral_calls_limit": 0,
        "tavily_calls_limit": 10,
        "serper_calls_limit": 10,
        "metaphor_calls_limit": 0,
        "firecrawl_calls_limit": 0,
        "stability_calls_limit": 10,
        "exa_calls_limit": 10,
        "video_calls_limit": 2,
        "image_edit_calls_limit": 5,
        "audio_calls_limit": 10,
        "wavespeed_calls_limit": 0,
        "gemini_tokens_limit": 50000,
        "openai_tokens_limit": 0,
        "anthropic_tokens_limit": 0,
        "mistral_tokens_limit": 0,
        "monthly_cost_limit": 2.0,
        "features": ["basic_content_generation", "limited_research"],
        "description": "Perfect for trying out ALwrity",
        "is_active": True,
    },
    {
        "name": "Basic",
        "tier": "basic",
        "price_monthly": 29.0,
        "price_yearly": 290.0,
        "ai_text_generation_calls_limit": 500,
        "gemini_calls_limit": 1000,
        "openai_calls_limit": 500,
        "anthropic_calls_limit": 200,
        "mistral_calls_limit": 500,
        "tavily_calls_limit": 200,
        "serper_calls_limit": 200,
        "metaphor_calls_limit": 100,
        "firecrawl_calls_limit": 100,
        "stability_calls_limit": 25,
        "exa_calls_limit": 100,
        "video_calls_limit": 10,
        "image_edit_calls_limit": 25,
        "audio_calls_limit": 100,
        "wavespeed_calls_limit": 200,
        "gemini_tokens_limit": 100000,
        "openai_tokens_limit": 100000,
        "anthropic_tokens_limit": 100000,
        "mistral_tokens_limit": 100000,
        "monthly_cost_limit": 25.0,
        "features": ["full_content_generation", "advanced_research", "basic_analytics", "all_tools_access", "oss_models_priority"],
        "description": "Perfect for individuals and small teams. Access all ALwrity features with generous limits powered by OSS AI models.",
        "is_active": True,
    },
    {
        "name": "Pro",
        "tier": "pro",
        "price_monthly": 79.0,
        "price_yearly": 790.0,
        "ai_text_generation_calls_limit": 3000,
        "gemini_calls_limit": 5000,
        "openai_calls_limit": 2500,
        "anthropic_calls_limit": 1000,
        "mistral_calls_limit": 2500,
        "tavily_calls_limit": 1000,
        "serper_calls_limit": 1000,
        "metaphor_calls_limit": 500,
        "firecrawl_calls_limit": 500,
        "stability_calls_limit": 100,
        "exa_calls_limit": 500,
        "video_calls_limit": 30,
        "image_edit_calls_limit": 100,
        "audio_calls_limit": 100,
        "wavespeed_calls_limit": 500,
        "gemini_tokens_limit": 5000000,
        "openai_tokens_limit": 2500000,
        "anthropic_tokens_limit": 1000000,
        "mistral_tokens_limit": 2500000,
        "monthly_cost_limit": 100.0,
        "features": ["unlimited_content_generation", "premium_research", "advanced_analytics", "priority_support"],
        "description": "Perfect for growing businesses",
        "is_active": True,
    },
    {
        "name": "Enterprise",
        "tier": "enterprise",
        "price_monthly": 199.0,
        "price_yearly": 1990.0,
        "ai_text_generation_calls_limit": 0,
        "gemini_calls_limit": 0,
        "openai_calls_limit": 0,
        "anthropic_calls_limit": 0,
        "mistral_calls_limit": 0,
        "tavily_calls_limit": 0,
        "serper_calls_limit": 0,
        "metaphor_calls_limit": 0,
        "firecrawl_calls_limit": 0,
        "stability_calls_limit": 0,
        "exa_calls_limit": 0,
        "video_calls_limit": 0,
        "image_edit_calls_limit": 0,
        "audio_calls_limit": 0,
        "wavespeed_calls_limit": 0,
        "gemini_tokens_limit": 0,
        "openai_tokens_limit": 0,
        "anthropic_tokens_limit": 0,
        "mistral_tokens_limit": 0,
        "monthly_cost_limit": 500.0,
        "features": ["unlimited_everything", "white_label", "dedicated_support", "custom_integrations"],
        "description": "For large organizations with high-volume needs",
        "is_active": True,
    },
]
