/**
 * After Build Scenes: exact prompt sent to llm_text_gen for scene generation.
 */

import React, { useCallback, useState } from "react";
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Alert,
  Box,
  Button,
  Chip,
  Stack,
  Typography,
} from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import type { SceneBuildGeneration } from "../../../services/youtubeApi";

interface SceneGenerationMetaProps {
  generation?: SceneBuildGeneration | null;
  defaultExpanded?: boolean;
}

function PromptBlock({ label, text }: { label: string; text: string }) {
  return (
    <Box>
      <Typography variant="caption" sx={{ fontWeight: 600, color: "#6b7280" }}>
        {label}
      </Typography>
      <Box
        component="pre"
        sx={{
          mt: 0.5,
          p: 1.5,
          bgcolor: "#f8fafc",
          borderRadius: 1,
          whiteSpace: "pre-wrap",
          fontSize: "0.8125rem",
          color: "#374151",
          fontFamily: "inherit",
          m: 0,
          maxHeight: 360,
          overflow: "auto",
        }}
      >
        {text || "(empty)"}
      </Box>
    </Box>
  );
}

export const SceneGenerationMeta: React.FC<SceneGenerationMetaProps> = ({
  generation,
  defaultExpanded = false,
}) => {
  const [copyMessage, setCopyMessage] = useState<string | null>(null);

  const handleCopy = useCallback(async () => {
    if (!generation) {
      console.warn("[SceneGenerationMeta] Copy skipped: no generation metadata");
      return;
    }
    const payload = [
      "SYSTEM PROMPT",
      generation.system_prompt || "",
      "",
      "USER PROMPT",
      generation.user_prompt || "",
    ].join("\n");
    try {
      if (!navigator?.clipboard?.writeText) {
        throw new Error("Clipboard API unavailable");
      }
      await navigator.clipboard.writeText(payload);
      setCopyMessage("Copied exact prompt");
      console.info("[SceneGenerationMeta] Copied exact prompt", {
        promptLen: payload.length,
      });
    } catch (error) {
      console.error("[SceneGenerationMeta] Copy failed", error);
      setCopyMessage("Could not copy. Select the text instead.");
    }
  }, [generation]);

  if (!generation) {
    return null;
  }

  const llmCalled = generation.llm_called !== false;
  const reused = Boolean(generation.scenes_reused_from_plan);
  const customScript = Boolean(generation.custom_script_used);

  return (
    <Accordion
      defaultExpanded={defaultExpanded}
      disableGutters
      elevation={0}
      sx={{
        border: "1px solid #e5e7eb",
        borderRadius: "8px !important",
        mt: 2,
        "&:before": { display: "none" },
      }}
    >
      <AccordionSummary expandIcon={<ExpandMoreIcon />}>
        <Typography sx={{ fontWeight: 600, color: "#111827", fontSize: "0.9375rem" }}>
          Exact prompt sent to the LLM (scene build)
        </Typography>
      </AccordionSummary>
      <AccordionDetails>
        <Stack spacing={1.5}>
          <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
            <Chip
              size="small"
              label={`Gateway: ${generation.text_gateway || "llm_text_gen"}`}
            />
            {generation.configured_provider ? (
              <Chip size="small" label={`Provider: ${generation.configured_provider}`} />
            ) : null}
            <Chip
              size="small"
              color={llmCalled ? "success" : "default"}
              label={llmCalled ? "LLM called for scenes" : "Scenes built without scene LLM"}
            />
            {reused ? (
              <Chip size="small" label="Scenes reused from plan" />
            ) : null}
            {customScript ? (
              <Chip size="small" label="Custom script parsed" />
            ) : null}
            {generation.json_schema_applied ? (
              <Chip size="small" label="Structured JSON schema applied" />
            ) : null}
          </Stack>

          {!llmCalled ? (
            <Alert severity="info">
              Scenes were not generated by the scene LLM on this run (reused from plan or parsed
              from a custom script). The prompt below is what would be sent if scenes were
              generated from the plan.
            </Alert>
          ) : null}

          <PromptBlock label="System prompt" text={generation.system_prompt || ""} />
          <PromptBlock label="User prompt" text={generation.user_prompt || ""} />
          <Button
            variant="outlined"
            size="small"
            onClick={handleCopy}
            sx={{ alignSelf: "flex-start", textTransform: "none" }}
          >
            Copy exact prompt
          </Button>
          {copyMessage ? (
            <Typography variant="caption" sx={{ color: "#6b7280" }}>
              {copyMessage}
            </Typography>
          ) : null}
        </Stack>
      </AccordionDetails>
    </Accordion>
  );
};
