import React from "react";
import "@testing-library/jest-dom/vitest";
import { render, screen } from "@testing-library/react";
import { SceneGenerationMeta } from "./SceneGenerationMeta";
import type { SceneBuildGeneration } from "../../../services/youtubeApi";

const generation: SceneBuildGeneration = {
  text_gateway: "llm_text_gen",
  configured_provider: "wavespeed",
  system_prompt: "You are a master YouTube scriptwriter.",
  user_prompt: "**VIDEO PLAN:**\nSummary: Budget travel tips",
  json_schema_applied: true,
  llm_called: true,
  scenes_reused_from_plan: false,
  custom_script_used: false,
};

describe("SceneGenerationMeta", () => {
  it("shows exact scene-build prompt", () => {
    render(<SceneGenerationMeta generation={generation} />);

    expect(screen.getByText("Exact prompt sent to the LLM (scene build)")).toBeInTheDocument();
    expect(screen.getByText(/Budget travel tips/)).toBeInTheDocument();
    expect(screen.getByText(/LLM called for scenes/)).toBeInTheDocument();
    expect(screen.getByText(/Gateway: llm_text_gen/)).toBeInTheDocument();
  });

  it("shows info when scenes were reused without LLM", () => {
    render(
      <SceneGenerationMeta
        generation={{
          ...generation,
          llm_called: false,
          scenes_reused_from_plan: true,
        }}
      />,
    );

    expect(screen.getByText(/Scenes reused from plan/)).toBeInTheDocument();
    expect(
      screen.getByText(/Scenes were not generated by the scene LLM on this run/),
    ).toBeInTheDocument();
  });

  it("does not imply the LLM user prompt produced parsed custom-script scenes", () => {
    render(
      <SceneGenerationMeta
        generation={{
          ...generation,
          llm_called: false,
          custom_script_used: true,
          user_prompt: "**VIDEO PLAN:**\nThis viral prompt did not generate the cards",
        }}
      />,
    );

    expect(
      screen.getByText("Scenes parsed from expanded script (scene LLM was not used)"),
    ).toBeInTheDocument();
    expect(screen.queryByText("Exact prompt sent to the LLM (scene build)")).not.toBeInTheDocument();
    expect(
      screen.getByText(/parsed from the expanded full script/i),
    ).toBeInTheDocument();
    expect(screen.getByText(/did not produce these scenes/i)).toBeInTheDocument();
    expect(screen.getByText("Copy reference prompt (not used on this run)")).toBeInTheDocument();
  });

  it("renders nothing without generation metadata", () => {
    const { container } = render(<SceneGenerationMeta generation={null} />);
    expect(container).toBeEmptyDOMElement();
  });
});
